### ISSUE TITLE
Grid css/layout is not loading correctly when Icon component is also used

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-blazor#127]
![image](https://github.com/user-attachments/assets/a91509bb-ccc9-490e-ac1c-4c281ea04223)

[state-persistence-main.zip](https://github.com/user-attachments/files/16679591/state-persistence-main.zip)

Issue found in 24.1.32

**Comment by gmurray81** [comment]
@damyanpetev @ChronosSF 

my theory is that some change has been made to the angular grid css that isn't updated in the pre-built grid theme for the Angular Elements grid and this is causing the icons to break.

If I add this style to the blazor sample that @mddifilippo89 linked:

```html
<style>
    .igx-icon.material {
        font-family: 'Material Icons';
        font-weight: normal;
        font-style: normal;
        font-size: 24px;
        line-height: 1;
        letter-spacing: normal;
        text-transform: none;
        display: inline-block;
        white-space: nowrap;
        word-wrap: normal;
        direction: ltr;
        -webkit-font-feature-settings: 'liga';
        -webkit-font-smoothing: antialiased;
    }
</style>
```

Then the icons load. Was there some change to the class that gets applied to the igx-icons in igx-grid that needs to be reconciled with the pre-built angular elements css?

**Comment by MayaKirova** [comment]
At first glance there's a mismatch between the classes applied to the icons.

For Blazor:
![image](https://github.com/user-attachments/assets/469ba18f-6737-45a1-94c8-3fe98f7a2bd2)

For Angular:
![image](https://github.com/user-attachments/assets/9698b0fd-78c2-408b-b265-f9d8c80fcfa7)

I'm guessing there's some version mismatch, since if the same classes as in Angular are applied to the Blazor icon it shows correctly.

**Comment by MayaKirova** [comment]
Actually, looking at the sample, it seems to be registering some icons as material:
```
                this.IconRef.RegisterIconFromText("restore", restoreIcon, "material");
                this.IconRef.RegisterIconFromText("save", saveIcon, "material");
                this.IconRef.RegisterIconFromText("clear", clearIcon, "material");
                this.IconRef.RegisterIconFromText("forward", forwardIcon, "material");
                this.IconRef.RegisterIconFromText("delete", deleteIcon, "material");
                this.IconRef.RegisterIconFromText("refresh", refreshIcon, "material");
```

This seems to break some of the existing icons, changing their class to "material" as well.

**Comment by damyanpetev** [comment]
The `igx-icon.material` class is provided from the style loaded from Material Icons font (e.g. from https://fonts.googleapis.com/icon?family=Material+Icons) which is normally a normal requirement for the Grid. It's also included by default IIRC.

@mddifilippo89 Is this similar sample to the we were looking at yest/monday for Grid state, because the one I threw around I had also tested updated to `24.1.32` and saw no issues with icons. Lemme see what's different in this one.

**Comment by MayaKirova** [comment]
Related to: https://github.com/IgniteUI/igniteui-angular/issues/14657
